# Generated by Django 2.1.7 on 2019-03-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=30)),
                ('size', models.IntegerField(default=100000)),
                ('currency', models.CharField(max_length=5)),
                ('maturity', models.DateField()),
                ('legal_name', models.CharField(max_length=30)),
            ],
        ),
    ]
